export const skills = [
    "Semantic & accessible HTML",
    "Error handling",
    "Git",
    "Responsive Web Desing",
    "React",
    "GitHub Pull Requests & Review",
    "JavaScript: ES6+",
    "React Hooks",
    "NPM",
    "Working with API (fetch,axios)",
    "Redux (Toolkit)",
    "Immutability",
    "Promises, Async/Await",
    "Redux-Saga",
    "Markdown",
    "Debugging",
    "React Router",
    "Scrum",
    "Css Flexbox",
    "CSS Grid",
    "Trello",
    "Teamwork",
    "CSS BEM convention",
];

export const nextSkills = [
    "JS classes",
    "Unit testing",
    "Node.js",
    "TypeScript",
    "Cypress",
    "React Context",
];